global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - '/etc/prometheus/alerting/*'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9092']
  - job_name: 'ceph'
    honor_labels: true
    static_configs:
      - targets: ['192.168.200.201:9283']
        labels:
          instance: 'ceph_cluster'
      - targets: ['192.168.200.202:9283']
        labels:
          instance: 'ceph_cluster'
      - targets: ['192.168.200.203:9283']
        labels:
          instance: 'ceph_cluster'
  - job_name: 'node'
    static_configs:
      - targets: ['192.168.200.202:9100']
        labels:
          instance: "ceph-2"
      - targets: ['192.168.200.203:9100']
        labels:
          instance: "ceph-3"
      - targets: ['192.168.200.207:9100']
        labels:
          instance: "client207"
      - targets: ['192.168.200.217:9100']
        labels:
          instance: "client217"
      - targets: ['10.121.143.202:9100']
        labels:
          instance: "ceph-2"
  - job_name: 'grafana'
    static_configs:
      - targets: ['192.168.200.201:9100']
        labels:
          instance: "ceph-1"
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: ['192.168.200.201:9093']
