global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'ceph-dashboard'
receivers:
- name: 'ceph-dashboard'
  webhook_configs:
  - url: 'http://ceph-1:8443/api/prometheus_receiver'
  - url: 'http://ceph-2:8443/api/prometheus_receiver'
  - url: 'http://ceph-3:8443/api/prometheus_receiver'
